### ISSUE TITLE
Missing Essential Files - main.py and requirements.txt

### ISSUE THREAD

**Issue by adarsh-site** [FarhaKousar1601/Criminal-DBMS#3]
<img width="947" alt="issue" src="https://github.com/FarhaKousar1601/Criminal-DBMS/assets/120160355/f13f06d8-067c-4cd0-8814-c13f19b1aa00">

**Comment by FarhaKousar1601** [comment]
Okay

**Comment by adarsh-site** [comment]
@FarhaKousar1601 Unfortunately, due to unforeseen circumstances, I won't be able to continue working on this issue. So, please assign it to someone else.
